"""Patch the autogenerated migration to include the tenant slug column."""
path = '/app/alembic/versions/3c4f0c0c0e74_add_tenant_slug.py'

with open(path) as f:
    content = f.read()

slug_upgrade = (
    "    op.add_column('tenants', sa.Column('slug', sa.String(100), nullable=True))\n"
    "    op.execute(\"UPDATE tenants SET slug = CONCAT('tenant-', CAST(id AS TEXT)) WHERE slug IS NULL\")\n"
    "    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=True)\n"
)

slug_downgrade = (
    "    op.drop_index('ix_tenants_slug', table_name='tenants')\n"
    "    op.drop_column('tenants', 'slug')\n"
)

# Insert slug DDL at the top of upgrade()
old_upgrade_marker = "    # ### commands auto generated by Alembic - please adjust! ###\n    op.alter_column('clients'"
new_upgrade_block = (
    "    # ### commands auto generated by Alembic - please adjust! ###\n"
    + slug_upgrade
    + "    op.alter_column('clients'"
)
content = content.replace(old_upgrade_marker, new_upgrade_block, 1)

# Insert slug DDL at the top of downgrade()
old_downgrade_marker = "    # ### commands auto generated by Alembic - please adjust! ###\n    op.alter_column('tenants'"
new_downgrade_block = (
    "    # ### commands auto generated by Alembic - please adjust! ###\n"
    + slug_downgrade
    + "    op.alter_column('tenants'"
)
content = content.replace(old_downgrade_marker, new_downgrade_block, 1)

with open(path, 'w') as f:
    f.write(content)

print("Migration patched successfully")
print(content)
