
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS car_make VARCHAR(100);
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS car_year INTEGER;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS vin VARCHAR(17);
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS notes TEXT;
