"""Add multi-tenancy models

Revision ID: 7a15984c2813
Revises: 70507f768c30
Create Date: 2026-02-20 17:59:30.903965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a15984c2813'
down_revision: Union[str, Sequence[str], None] = '70507f768c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bot_token', sa.String(length=255), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('tariff', sa.Enum('FREE', 'STANDARD', 'PRO', name='tariff'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', name='tenantstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_token')
    )
    op.add_column('appointments', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'tenants', ['tenant_id'], ['id'])
    op.add_column('clients', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('clients', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index('ix_clients_phone', table_name='clients')
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_foreign_key(None, 'clients', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('clients', 'vehicle_info')
    op.add_column('services', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_foreign_key(None, 'services', 'tenants', ['tenant_id'], ['id'])
    op.add_column('shops', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('shops', sa.Column('phone', sa.String(length=20), nullable=True))
    op.alter_column('shops', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('shops', 'address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=True)
    op.create_foreign_key(None, 'shops', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.alter_column('users', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.alter_column('shops', 'address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('shops', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('shops', 'phone')
    op.drop_column('shops', 'tenant_id')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.alter_column('services', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('services', 'description')
    op.drop_column('services', 'tenant_id')
    op.add_column('clients', sa.Column('vehicle_info', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.create_index('ix_clients_phone', 'clients', ['phone'], unique=True)
    op.alter_column('clients', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('clients', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'tenant_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'notes')
    op.drop_column('appointments', 'tenant_id')
    op.drop_table('tenants')
    # ### end Alembic commands ###
