"""add tariff plans and encrypted bot tokens

Revision ID: c8a31e2b0316
Revises: 1ec2ee882e05
Create Date: 2026-02-20 18:30:33.835072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8a31e2b0316'
down_revision: Union[str, Sequence[str], None] = '1ec2ee882e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_appointments', sa.Integer(), nullable=False),
    sa.Column('max_shops', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('tenants', sa.Column('encrypted_bot_token', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('bot_token_hash', sa.String(length=64), nullable=True))
    op.add_column('tenants', sa.Column('tariff_plan_id', sa.Integer(), nullable=True))
    op.drop_constraint('tenants_bot_token_key', 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_bot_token_hash'), 'tenants', ['bot_token_hash'], unique=True)
    op.create_unique_constraint(None, 'tenants', ['encrypted_bot_token'])
    op.create_foreign_key(None, 'tenants', 'tariff_plans', ['tariff_plan_id'], ['id'])
    op.drop_column('tenants', 'tariff')
    op.drop_column('tenants', 'bot_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('bot_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('tariff', postgresql.ENUM('FREE', 'STANDARD', 'PRO', name='tariff'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_bot_token_hash'), table_name='tenants')
    op.create_unique_constraint('tenants_bot_token_key', 'tenants', ['bot_token'])
    op.drop_column('tenants', 'tariff_plan_id')
    op.drop_column('tenants', 'bot_token_hash')
    op.drop_column('tenants', 'encrypted_bot_token')
    op.drop_table('tariff_plans')
    # ### end Alembic commands ###
